### ISSUE TITLE
Refatorar o parser de disciplinas

### ISSUE THREAD

**Issue by gabisurita** [unicampi/unicampi#15]
Refatorar o parser de disciplinas para não utilizar burca por conteúdo.

Relacionado ao #6.

**Comment by lucasdavid** [comment]
won't fix?

**Comment by gabisurita** [comment]
Não acho que seja... isso não é muito difícil de resolver e acho que pode trazer benefícios. Como resolver o #6 de graça. O menu de disciplinas também contém as disciplinas correntes com informações mais completas que o menu de oferecimentos na alteração de matrícula.
