### ISSUE TITLE
Fazer as buscas por id case insensitive

### ISSUE THREAD

**Issue by gabisurita** [unicampi/unicampi#38]
Eu acho que não faz sentido as duas requests terem respostas diferentes:

`http://gabsurita.pythonanywhere.com/institutos/IC` (Ok)
`http://gabsurita.pythonanywhere.com/institutos/ic`  (404)

**Comment by lucaskatayama** [comment]
Eu acho que é uma questão de padrão....

Obtém UM instituto pelo ID, aqui case sensitive 
```
GET
/institutos/{ID} 
```

Busca por Institutos,  aqui case insensitive
```
GET
/institutos/?q={BUSCA}
```

**Comment by gabisurita** [comment]
Padrão em que sentido? Se pensamos o modelo de dados acho que faz sentido, por isso inclusive acho que isso deve ser tratado nos Resources, mas exigir nos endpoints da API eu acho um certo excesso de rigor. Por mais que seja consistente com o modelo de dados, os id são siglas de instituto/disciplina, e considerar uma request mal formulada por exigir upper case é, na minha opinião, um pouco deselegante.

**Comment by lucaskatayama** [comment]
REST...
Exigir uppercase não acho deselegante desde que a informação esteja consistente.
por exemplo... Se eu requisito uma lista de recursos abaixo do /instituto o id usado para obter um instituto deve ser o mesmo em /instituto/{ID}, independente de ser uppper/lower....

O que eu acho que não deveria ser é utilizar ambos...

Eu não curto strings com significados para ids... prefiro hashs, apesar de serem mais difíceis de entender.... serão únicos na vida.. teríamos problemas por exemplo um dia IMECC foi IME, da´i muda a sigla muda o banco.... e assim vai o problema.... Mas isso pensando em coisa lá pra frente de ter algo salvo  e talz...

Por agora... sendo que sempre vai na DAC e pega a informação.... o mais simples melhor...

**Comment by gabisurita** [comment]
Eu não acho que case-insentive viole principios de REST.

Não precisa ir longe...
https://github.com/unicampi/unicampi/
https://github.com/unicampi/UNICAMPI/

**Comment by lucaskatayama** [comment]
huummm... isso eh novo pra mim... 

sempre trabalhei como ID sendo unico dado que uma url eh uma path para um recurso.. 
vide as pastas do Linux ```/home/Lucas != /home/lucas```

Excluindo a idéia de isso ser padrão ou não, o que eu acho que ainda não é:

essas 3 uris (a segunda tah dando 404) levariam sempre para um mesmo recurso ?
entao em todas as paths vc teria um trabalho de normalizar para encontrar ?
se sim... Vc estaria trabalhando para consertar um typo do user certo?

Então estaria se ajustando para o usuário?
Então trabalhando em pró dele?

Se a resposta eh sim para essa última, acho válido a idéia...

**Comment by gabisurita** [comment]
> essas 3 uris (a segunda tah dando 404) levariam sempre para um mesmo recurso ?
Sim. A segunda estava faltando um "I", mas acho que a ideia ficou clara.

> entao em todas as paths vc teria um trabalho de normalizar para encontrar ?
Sim, mas um trabalho que é bem pequeno se o modelo de dados é claro. 

> Vc estaria trabalhando para consertar um typo do user certo?
Sim. A ideia é que eu acho completamente contraintuitivo um usuário receber um 404 quando buscando por uma disciplina e usando a sigla em minúsculo, afinal, na prática, o id é uma sigla (poderia ser até um 301, mas 404 e um exagero). Quando a gente pensa em um cliente bem implementado, esse tipo de problema não deve ocorrer. Mas pra que deixar dessa forma se é tao simples resolver isso do lado do servidor?

**Comment by gabisurita** [comment]
Closed by  #44
