### ISSUE TITLE
Chegar em 100% de cobertura

### ISSUE THREAD

**Issue by gabisurita** [unicampi/unicampi#45]
Certa vez eu ouvi de um especialista em *Fuzzy Testing* da Mozilla:
> "I tend to think that a 100% coverage for Python project is a minimum."

**Comment by lucasdavid** [comment]
Também precisa setar a estratégia do coverage pra `all-branches` e exluir linhas como `pass` ou `raise NotImplementedError`. Eu costumo escrever o arquivo `.coveragerc` igual ao abaixo, mas por algum motivo ele não ta sendo carregado automaticamente pelo coverage usando o tox :(

```shell
[run]
source = unicampi
include = unicampi*
branch = True

[report]
exclude_lines =
    pass
    raise NotImplementedError
    if __name__ == .__main__.:
omit =
    */tests/*
    */python?.?/*
    */site-packages/nose/*
```

**Comment by gabisurita** [comment]
Adicionei os ignores em https://github.com/unicampi/unicampi/commit/b42e5a7011c60855e37992b26c2c4122aca8cb9f . Acho que está funcionando normalmente...

**Comment by lucasdavid** [comment]
Obrigado! (:
