### ISSUE TITLE
Mudança nas rotas de oferecimentos e matriculas?

### ISSUE THREAD

**Issue by lucasdavid** [unicampi/unicampi#48]
Eu normalmente vejo o termo `Offerings` associado a ideia de "oferenda" (e.g. oferenda aos deuses). Será que nós poderíamos renomear esse recurso pra `Classes` ou `Lectures`?

Além disso, nesse momento, as rotas pras Ofertas e Matriculas estão assim, respec.:

`/periodos/{periodo}/oferecimentos/{disciplina}/turmas`
`/periodos/{periodo}/oferecimentos/{disciplina}/turmas/{turma}/matriculados`

Eu acho um pouco confuso o parâmetro {disciplina} vir logo depois de "oferecimentos". E se fosse assim:

`/disciplinas/{disciplina}/periodos/{periodo}/turmas`
`/disciplinas/{disciplina}/periodos/{periodo}}/turmas/{turma}matriculas`

A rota `/disciplinas/{id}` já existe, então ia encaixar perfeito com ela.

**Comment by gabisurita** [comment]
> Eu normalmente vejo o termo Offerings associado a ideia de "oferenda" (e.g. oferenda aos deuses). Será que nós poderíamos renomear esse recurso pra Classes ou Lectures?

Sem dúvida. aportuguesei isso demais...

> Eu acho um pouco confuso o parâmetro {disciplina} vir logo depois de "oferecimentos". 

Eu concordo, mas a PR #49 inclui `periodos/{periodo}` também para `disciplinas` e `insitutos`,
daí ficaremos com:

```
/disciplinas/{disciplina}/periodos/{periodo}
/disciplinas/{disciplina}/periodos/{periodo}/turmas
/disciplinas/{disciplina}/periodos/{periodo}/turmas/{turma}/matriculas
```

E quem sabe com a #40, temos finalmente:

```
/disciplinas/{disciplina}
/disciplinas/{disciplina}/periodos/{periodo}  # para as disciplinas ativas
/disciplinas/{disciplina}/periodos/{periodo}/turmas
/disciplinas/{disciplina}/periodos/{periodo}/turmas/{turma}/matriculas
```

**Comment by gabisurita** [comment]
E também acho que podemos trocar:
```
/periodos/{periodo}/institutos/{instituto}/disciplinas
```
Por:
```
/disciplinas/{disciplina}/periodos/{periodo}/institutos/{instituto}
```

**Comment by gabisurita** [comment]
E também acho que podemos trocar:

```
/institutos
/institutos/{instituto}     # PR #34
/institutos/{instituto}/periodos/{periodo}    # Institutos ativos
/institutos/{instituto}/periodos/{periodo}/disciplinas
```

**Comment by lucasdavid** [comment]
Legal. Ficou muito bom. :)
