### ISSUE TITLE
Resposta da API com caracteres especiais

### ISSUE THREAD

**Issue by lucaskatayama** [unicampi/unicampi#55]
**Description:**
A API está retornando alguns caracteres especiais nos campos. Acho que a captura não está transformando em UTF-8.

**Actual:**
```
{
  "website": "http://www.ic.unicamp.br/",
  "sigla": "IC",
  "nome": "Instituto de ComputaÃ§Ã£o"
}
```
**Expected:**
```
{
  "website": "http://www.ic.unicamp.br/",
  "sigla": "IC",
  "nome": "Instituto de Computação"
}   
```
**Steps to reproduce:**
1. Acessar a api para instituto IC: http://gabsurita.pythonanywhere.com/institutos/IC
2. Done.

**Comment by gabisurita** [comment]
Same as #51.
